name: 'Compare Coverage'
description: 'Compare unit test coverage between releases'
inputs:
  previous_data:
    description: 'coverage data from previous release'
    required: true
  current_data:
    description: 'coverage data from current release'
    required: true
outputs:
  comparison:
    description: 'comparison result'
  current_average_coverage:
    description: 'average coverage result for current release'
runs:
  using: 'node16'
  main: 'dist/index.js'