name: 'Send Check Status'
description: 'Send check status to commit sha based on action run status'
inputs:
  check_context:
    description: 'check context to be sent'
    default: 'job_completion'
  sha:
    description: 'sha of the commit'
    required: true
  token:
    description: 'github token'
    required: true
  is_success:
    description: 'status to be sent'
    required: true
    default: true
  success_message:
    description: 'success message to be sent'
    default: 'Job completed'
  failure_message:
    description: 'failure message to be sent'
    default: 'Job failed'
  notify_on_failure:
    description: 'whether to send a message to slack if the job fails'
    required: false
    default: false
    
  # Inputs for notify on failure. 
  # If notify_on_failure is true, all inputs below must be filled in
  slack_webhook_url:
    description: 'slack webhook url'
    required: false
  app_version:
    description: 'app version of the build'
    required: false
  head_ref:
    description: 'source branch'
    required: false
  base_ref:
    description: 'target branch'
    required: false
    
runs:
  using: "composite"
  steps:
    - name: set job status
      id: set-status
      run: |
        if [[ ${{ inputs.is_success }} = true ]]; then
          echo "job_state=success" >> $GITHUB_OUTPUT
          echo "job_description=${{ inputs.success_message }}" >> $GITHUB_OUTPUT
        else
          echo "job_state=failure" >> $GITHUB_OUTPUT
          echo "job_description=${{ inputs.failure_message }}" >> $GITHUB_OUTPUT
        fi
      shell: bash

    - name: send status
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ inputs.sha }} \
        --header 'authorization: Bearer ${{ inputs.token }}' \
        --header 'content-type: application/json' \
        --data '{
          "context": "${{ inputs.check_context }}",
          "state": "${{ steps.set-status.outputs.job_state }}",
          "description": "${{ steps.set-status.outputs.job_description }}",
          "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        }'
      shell: bash
      
    - name: notify on failure
      if: ${{ inputs.notify_on_failure == 'true' && inputs.is_success == 'false' }}
      uses: slackapi/slack-github-action@v1
      with:
        payload: |
          {
            "text": "Hi, <!subteam^S031A5Q1C0Y|@app-engineers> Build ${{ inputs.app_version }} failed on ${{ github.event.comment.body }} commands.",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "text": "*CI/CD for ${{ inputs.head_ref }} failed on ${{ github.event.comment.body }} commands. you can see the details on <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}| Detail Actions>",
                  "type": "mrkdwn"
                }
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "${{ inputs.head_ref }} → ${{ inputs.base_ref }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK